### ISSUE TITLE
STARTER TASK - WebUI - Device Pages (Lab Access Not Required)

### ISSUE THREAD

**Issue by palisadoes** [UWICompSociety/infoset#11]
The report pages for individual devices are very bland. The output is created using plain HTML. It would be good to have a  web interface that reads the YAML data for the devices and  presents it in a modern Web 2.0 style.

1. **Bad**: http://calico.palisadoes.org/infoset/192.168.1.3.html
2. **Better**: http://calico.palisadoes.org/switchmap/www/switches/192.168.1.3.html

You can make it ***best!***

At a minimum we'll need:

1. Different CSS colors for up / down ports.
2. Colored headings

Maintain this aspect of the current design:

1. If a port is a trunk port, only put the ***Native*** VLAN in the VLAN column. This is keyed `jm_vlan` by the Translator class.
2. If a port is not a trunk port, put the regular ***non-Native*** VLAN. This is keyed `jm_nativevlan` by the Translator class.
3. There should be another section on the page for trunked VLANs where there is a drill down to view all VLAN data for the port.

You can work on this project as long as you have valid sample YAML data in your **data/snmp** directory. This data would come from a successful poll either in the lab or on some other system. YAML device data can be obtained here: http://calico.palisadoes.org/infoset/yaml

Web frameworks are fine, as long as they use off the shelf packages that are available on Fedora, RedHat, CENTOS and Ubuntu. No custom repositories.

**Comment by Pr0x1m4** [comment]
TODO: asignee Kimberly Simmonds
