### ISSUE TITLE
STARTER TASK - WebUI - Home Page (Lab Access Not Required)

### ISSUE THREAD

**Issue by palisadoes** [UWICompSociety/infoset#12]
The home page for infoset is very bland. There is the possibility of converting it to a global status page for the network.

1. **Bad**: http://calico.palisadoes.org/infoset/
2. **Better**: http://calico.palisadoes.org/switchmap/www/index.html

You can make it **best**!

Some features that could be added could be:

1. A status table for each device showing information such as percentage port utilization, CPU utilization, operating system version, manufacturer, model number, name.
2. Overall status on system wide port utilization, counts of each type of device, operating systems etc. on the network.
3. The ability to download this data as a CSV
4. Possibility of charting port utilization rates over time. 

You can work on this project as long as you have valid sample YAML data in your **data/snmp** directory. This data would come from a successful poll either in the lab or on some other system. YAML device data can be obtained here: http://calico.palisadoes.org/infoset/yaml

**Comment by Pr0x1m4** [comment]
TODO: asignee Kimberly Simmonds

**Comment by Pr0x1m4** [comment]
Proposed design for Homepage
![garnet-homepage-mock-01](https://cloud.githubusercontent.com/assets/4820517/15874833/c77a4968-2cca-11e6-962f-c52c8533ecdc.png)

**Comment by Pr0x1m4** [comment]
@ksimmonds for now work on the sidebar that lists all the hosts
