### ISSUE TITLE
API Creation - Device Data (Lab Access Not Required)

### ISSUE THREAD

**Issue by palisadoes** [UWICompSociety/infoset#13]
To be really useful infoset should be able to expose device data through an API. The data should have the option of being password protected using local accounts or external sources such as LDAP

The API should be designed in such a way that it could be used by the Web Frontend as its exclusive source of data.

You can work on this project as long as you have valid sample YAML data in your **data/snmp** directory. This data would come from a successful poll either in the lab or on some other system. YAML device data can be obtained here: http://calico.palisadoes.org/infoset/yaml

**Comment by Pr0x1m4** [comment]
TODO: asignee, Luke Chen Shui

**Comment by chenshuiluke** [comment]
Okay, I added the ability to get a specific device from a layer, for e.g. http://localhost:5000/hosts/192.168.1.2/layer1/1 returns:

    {
      "c2900PortDuplexStatus": 1,
      "c2900PortLinkbeatStatus": 2,
      "ifAdminStatus": 1,
      "ifAlias": "",
      "ifDescr": "VLAN1",
      "ifHighSpeed": 10,
      "ifInOctets": 77673052,
      "ifIndex": 1,
      "ifLastChange": 1795,
      "ifName": "VL1",
      "ifOperStatus": 1,
      "ifOutOctets": 54711517,
      "ifPhysAddress": "00307bdc9480",
      "ifSpeed": 10000000,
      "ifType": 6
    }

**Comment by chenshuiluke** [comment]
You can also get layer 3 stuff with `http://localhost:5000/hosts/192.168.1.2/layer3`:

    {
      "ipNetToMediaTable": {
        "192.168.1.2": "00307bdc9480",
        "192.168.1.200": "001ec9ac3e7b"
      }
    }

**Comment by chenshuiluke** [comment]
If you guys could tell me what kind of data you would like to be able to get that would be a great help

**Comment by Pr0x1m4** [comment]
Looks great,

Ideally the API should return data on each port on a host as seen in (SwitchMap)[http://calico.palisadoes.org/switchmap/www/switches/192.168.1.1.html] Port tables.

Let's say if a route like `/hosts/<host>/layer1/ports` existed, it would return a list of ports and their details to be used to populate the table. It would be wise to take a look on tables that (SwitchMap)[http://calico.palisadoes.org/switchmap/www/switches/192.168.1.1.html] has.

Possible routes:
`/hosts/<host>/layer1/ports` Returns all ports on a switch/host
`hosts/<host>/layer1/ports/<port_number>/state` Returns the status of port on a specific host
`/hosts/<host>/layer1/vlans` Returns all vlans on a switch/host

**Comment by chenshuiluke** [comment]
Okay, as of right now, `http://localhost:5000/hosts/192.168.1.1/layer1` returns all the layer1 ports.
`http://localhost:5000/hosts/192.168.1.1/layer1/122/ifDescr` returns the value for that port's ifDescr field. That works for all fields of the port, so it can return, say, ifType as well `http://localhost:5000/hosts/192.168.1.1/layer1/122/ifType`:

    6
