### ISSUE TITLE
WebUI - Architecture (Lab Access Not Required)

### ISSUE THREAD

**Issue by palisadoes** [UWICompSociety/infoset#15]
There needs to be general guidelines created for the creation of a web UI. 

Design guidelines should consider the following:

1. The WebUI needs to work out of the box without the need to install any non-standard Linux packages or frameworks. Simplicity of installation and setup must be a primary goal to ensure acceptance.
2. The WebUI needs to use existing device YAML data via the class in xlate_snmp or longer term via the API that has been created as an issue.

You can work on this project as long as you have valid sample YAML data in your **data/snmp** directory. This data would come from a successful poll either in the lab or on some other system. Contact your mentor on how to get valid files.

**Comment by Pr0x1m4** [comment]
Issue resolved by commit d1876046a3a1fa35ad5a758925cfba155c5994b6
