### ISSUE TITLE
Set CLI route for snmp Polling/Monitoring

### ISSUE THREAD

**Issue by Pr0x1m4** [UWICompSociety/infoset#44]
Add an argument to toolbox.py for snmp monitoring.

Files involved
`toolbox.py`

**Comment by Pr0x1m4** [comment]
Also check
`infoset/interfaces/jm_cli.py`

**Comment by chenshuiluke** [comment]
Okay I think I did what you asked

**Comment by chenshuiluke** [comment]
It now recognizes 'monitor' as an argument but doesn't do anything

**Comment by Pr0x1m4** [comment]
Issue became redundant
Closing.
